config/routes.rb
Rails.application.routes.draw do
  
  resources :areas
  resources :topicos do
    resources :comentarios
  end

  root 'topicos#index'

  devise_for :users, controllers: {registrations: 'registrations'}

end

app/models/comentario.rb
class Comentario < ApplicationRecord

    belongs_to :topico
    belongs_to :user
    validates :comentario, presence: true

    extend FriendlyId
    friendly_id :reply, use: [:slugged, :finders]

    def should_generate_new_friendly_id?
	comentario_changed?
    end

end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
    before_action :authenticate_user!
    before_action :set_comentario, only: [:edit, :update, :show, :destroy]
    before_action :set_topico, only: [:create, :edit, :show, :update, :destroy]

    def create
        @comentario = @topico.comentarios.create(params[:comentario].permit(:comentario, :topico_id))
        @comentario.user_id = current_user.id

        respond_to do |format|
            if @comentario.save
                format.html { redirect_to topico_path(@topico) }
                format.js 
            else
                format.html { redirect_to topico_path(@topico), notice: 'Comentário não salvo. Tente novamente.'}
                format.js
            end
        end
    end

    def new
    end

    def destroy
        @comentario = @topico.comentarios.find(params[:id])
        @comentario.destroy
        redirect_to topico_path(@topico)
    end

    def edit
        @topico = Topico.find(params[:topico_id])
        @comentario = @topico.comentarios.find(params[:id])
    end

    def update
        @comentario = @topico.comentarios.find(params[:id])
        respond_to do |format|
            if @comentario.update(comentario_params)
                format.html {  redirect_to topico_path(@topico), notice: 'Comentário atualizado com sucesso.'}
            else
                format.html { render :edit }
                format.json { render json: @comentario.errors, status: :unprocessable_entity}
            end
        end
    end

    def show
    end

    private

    def set_topico
        @topico = Topico.find(params[:topico_id])
    end

    def set_comentario
        @comentario = Comentario.find(params[:id])
    end

    def comentario_params
        params.require(:comentario).permit(:comentario)
    end
end

app/views/comentarios/_comentario.html.erb
<div class="box">
 <article class="media">
  <div class="media-left">
   <figure class="image is-64x64">
    <%= gravatar_image_tag(comentario.user.email, class: 'border-radius-50', size: 48, alt: comentario.user.username) %>
   </figure>
  </div>
  <div class="media-content">
    <div class="content">
     <p>
      <strong><%= comentario.user.username %></strong> <small><%= time_ago_in_word(comentario.created_at)%></small>
        <br/>
        <%= markdown(comentario.comentario) %>
    </p>
    </div>
    <% if comentario_author(comentario) || has_role?(:admin) %>
    <nav class="level is-mobile">
    <div class="level-left">
    <a class="level-item">
     <%= link_to edit_topico_comentario_path(comentario.topico, comentario) do %>
        <span class="icon is-small"><i class="fa fa-pencil"></i></span>
        <% end%>
    </a>
    <a class="level-item">
     <%= link_to [comentario.topico, comentario], 
          method: :delete, data: {confirm: "Tem certeza?"} do %>
        <span class="icon is-small"><i class="fa fa-trash-o"></i></span>
        <% end%>
    </a> 
    </div>
    </nav>
     <% end %>
    </div>
    </article>
</div>
 

app/views/comentarios/_form.html.erb
<%= simple_form_for([@topico, @topico.comentarios.build], remote: true) do |f| %>

<div class="field">
 <div class="control">
    <%= f.input :comentario, input_html: {class: 'textarea' }, wrapper: false, label_html: { class: 'label' } %>
 </div>
</div>

<%= f.button :submit, 'Deixe um comentário', class:'button is-info' %>

<% end %>

app/views/comentarios/create.js.erb
$("<%= escape_javascript(render(@comentario)) %>").appendTo('#topico-comentarios');

app/views/comentarios/edit_html.erb
<h1 class="title is-2 has-text-gray">Editando Comentário</h1>

<%= simple_form_for([@topico, @comentario]) do |f|%>

<div class="field">
  <div class="control">
   <%= f.input :comentario, input_html: { class: 'textarea' }, wrapper: false, label_html: {class: 'label' } %>
</div>
</div>

<%= f.button :submit, 'Atualizar comentário', class:'button is-info' %>
<% end %>