config/routes.rb
Rails.application.routes.draw do
  
  resources :areas
  resources :topicos do
    resources :comentarios
  end

  root 'topicos#index'

  devise_for :users, controllers: {registrations: 'registrations'}

end

app/models/area.rb
class Area < ApplicationRecord
   
    has_many :topicos
    has_many :users, through: :topicos
    resourcify

    extend FriendlyId
    friendly_id :area, use: [:slugged, :finders]

    def should_generate_new_friendly_id?
      area_changed?
    end
    
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
    @topicos = Topico.all.order('created_at desc')
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
    @topicos = Topico.where('area_id = ?', @area.id)
    @areas = Area.all
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to areas_path, notice: 'Area criada com sucesso!' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to areas_path, notice: 'Area foi atualizada com sucesso!' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area foi destruida com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:area)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.erb
<%= simple_form_for(@area) do |f| %>
  <%= f.error_notification %>

<div class="field">
 <div class="control">
    <%= f.input :area, input_html: { class: 'input' }, wrapper:false, label_html: { class: 'label' } %>

  </div>
</div>

<%= f.button :submit, class: 'button is-info' %>

<% end %>

app/views/areas/edit.html.erb
<h1 class="title is-3">Editando Area</h1>

<%= render 'form', area: @area %>

app/views/areas/index.html.erb
<h1 class="title is-2">Areas</h1>

<% if has_role?(:admin) %>
<div class="level">
 <div class="level-left"></div>
 <div class="level-right">
   <%= link_to 'Nova Area', new_area_path, class:'button is-dark' %>
 </div>
</div>

<table class="table is-fullwidth">
 <thead>
   <tr>
     <th>Area</th>
     <th colspan="3"></th>
   </tr>
 </thead>
 <tbody>
   <% @areas.each do |area| %>
   <tr>
     <td><%= link_to area.area, area %></td>
     <td>
       <div class="buttons is-right">
         <%= link_to 'Ver Area', area, class:'button' %>
         <%= link_to 'Editar Area', edit_area_path(area), class:'button' %>
         <%= link_to 'Deletar', area, class:'button is-danger', method: :delete, data: { confirm: "Você tem certeza que quer deletar essa área? " } %>
       </div>
     </td>
   </tr>
   <% end %>
 </tbody>

</table>

<% else %>
<p class="has-text-center">Você não tem acesso para essa página.</p>
<% end %>

app/views/areas/new.html.erb
<div class="columns is-centered">
 <div class="column is-4">
  <h1 class="title is-3">Criar uma nova area</h1>
  <%= render 'form', area: @area %> 
 </div>
</div>

app/views/areas/show.html.erb
<div class="level">
 <div class="level-left">
 <h1 class="title-is-2"><%= @area.area %></h1>
 </div>
 <div class="level-right">
 <% if has_role?(:admin) %>
  <%= link_to 'Editar Area', edit_area_path(@area), class:"button" %>
 <% end %>
 </div>
</div>
<hr />

<div class="columns">
 <%= render 'shared/topicos' %>
 <%= render 'topicos/sidebar' %>
</div>