config/routes.rb
Rails.application.routes.draw do
  
  resources :areas
  resources :topicos do
    resources :comentarios
  end

  root 'topicos#index'

  devise_for :users, controllers: {registrations: 'registrations'}

end

app/models/topico.rb
class Topico < ApplicationRecord

    belongs_to :area
    belongs_to :user
    has_many :comentarios, dependent: :destroy

    validates :title, :content, presence: true
    resourcify
  
    extend FriendlyId
    friendly_id :title, use: [:slugged, :finders]

    def should_generate_new_friendly_id?
	title_changed?
    end
end

app/controllers/topicos_controller.rb
class TopicosController < ApplicationController
  before_action :set_topico, only: [:show, :edit, :update, :destroy]
  before_action :find_areas, only: [:index, :show, :new, :edit]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /topicos
  # GET /topicos.json
  def index
    @topicos = Topico.all.order('created_at desc')
  end

  # GET /topicos/1
  # GET /topicos/1.json
  def show
    @topicos = Topico.all.order('created_at desc')
  end

  # GET /topicos/new
  def new
    @topico = current_user.topicos.build
  end

  # GET /topicos/1/edit
  def edit
  end

  # POST /topicos
  # POST /topicos.json
  def create
    @topico = current_user.topicos.build(topico_params)

    respond_to do |format|
      if @topico.save
        format.html { redirect_to @topico, notice: 'Topico criado com sucesso!' }
        format.json { render :show, status: :created, location: @topico }
      else
        format.html { render :new }
        format.json { render json: @topico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topicos/1
  # PATCH/PUT /topicos/1.json
  def update
    respond_to do |format|
      if @topico.update(topico_params)
        format.html { redirect_to @topico, notice: 'Topico foi atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @topico }
      else
        format.html { render :edit }
        format.json { render json: @topico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topicos/1
  # DELETE /topicos/1.json
  def destroy
    @topico.destroy
    respond_to do |format|
      format.html { redirect_to topicos_url, notice: 'Topico foi destruido com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topico
      @topico = Topico.find(params[:id])
    end

    def find_areas
      @areas = Area.all.order('created_at desc')
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topico_params
      params.require(:topico).permit(:title, :content, :area_id)
    end
end

app/helpers/topicos_helper.rb
module TopicosHelper

  def topico_author(topico)
   user_signed_in? && current_user.id == topico.user_id
  end

  def comentario_author(comentario)
   user_signed_in? && current_user.id == comentario.user_id
  end


end

app/views/topicos/_form.html.erb
<%= simple_form_for(@topico) do |f| %>
  <%= f.error_notification %>

    <div class= "field">
      <div class="control">
        <%= f.input :title, required:true, input_html: { class: 'input'}, wrapper: false, label_html: {class: "label"} %>
      </div>
  </div>

      <div class= "field">
      <div class="control">
        <%= f.input :content, required:true, input_html: { class: 'textarea'}, wrapper: false, label_html: {class: "label"} %>
      </div>
  </div>

  <div class ="field">
    <label class="label">Area</label>
    <div class="control has-icons-left">
      <span class="select">
        <%= f.input_field :area_id, collection: @areas.map {|c|[c.area, c.id]}, prompt: "Selecione a area"%>
        </span>
        <span class="icon is-small is-left">
        <i class="fa fa-tag"></i>
        </span>
  </div>
  </div>

  <div class="field">
    <div class= "control">
      <%= f.button :submit, class: "button is-info"%>
      </div>
      </div>
<% end %>

app/views/topicos/_sidebar.html.erb
<div class="column is-3 is-offset-1">
    <h3 class="title is-5 has-text-grey-light">Areas </h3>

    <ul class= "list">
        <% @areas.each do |c| %>
        <li><%= link_to c.area, c %></li>
        <% end %>
    </ul>

    <br/>

    <% if has_role?(:admin) %>
    <%= link_to 'Nova Area', new_area_path, class:'button is-info' %>
    <% end %>

</div>

app/views/topicos/edit.html.erb
<h1 class="title is-3">Editando Topico</h1>

<%= render 'form', topico: @topico %>

app/views/topicos/index.html.erb
<div class = "columns">
  <%= render 'shared/topicos'%>
  <%= render 'sidebar' %>
</div>

app/views/topicos/new.html.erb
<h1 class= "title is-size-3">Novo Tópico</h1>

<%= render 'form', topico: @topico %>

<%= link_to 'Voltar', topicos_path %>

app/views/topicos/show.html.erb
<div class="columns">
  <div class="column is-8">
    <h1 class="title is-2 has-text-grey topico-title"><%= @topico.title %></h1>
    <h3 class="subtitle is-5 has-text-grey-lighter"> por <%= @topico.user.username %> em <%= link_to @topico.area.area, @topico.area %></h3>
    <div class="level">
      <div class="level-left"></div>
      <div class="level-right">
        <% if topico_author(@topico) %>
        <div class="buttons">
            <%= link_to 'Editar topico', edit_topico_path(@topico), class:'button'%>
            <%= link_to 'Deletar', topico_path(@topico), method: :delete, data: { confirm: "Deletar tópico?" }, class:'button' %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="content"><%= markdown(@topico.content) %></div>

    <h2 class="subtitle is-5 has-text-grey"><%= @topico.comentarios.count %> Comentarios</h2>

    <div id="topico-comentarios">
      <%= render @topico.comentarios %>
    </div>

    <hr />

    <h3 class="subtitle is-3 has-text-grey">Deixe um comentário</h3>
    <% if user_signed_in? %>
      <%= render 'comentarios/form' %>
    <% else %>
    <p>Para comentar você precisa <%= link_to 'Entrar na sua conta', new_user_session_path %>. Não possui conta? 
      <%= link_to 'Cadastre-se', new_user_registration_path %> agora!</p>
    <% end %>

  </div>

  <%= render 'sidebar' %>

</div>